name: cil_env
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - python=3.11.11
  - pip:
      - librecommender==1.5.1
      - numpy==1.23.4
      - pandas==2.2.3
      - scikit-learn==1.6.1
      - scikit-surprise==1.1.4
      - tensorflow==2.12.0
      - torch
      - torchaudio
      - torchvision
      - tqdm
      - scipy<1.14.0
